### ISSUE TITLE
Actual size of single person test set

### ISSUE THREAD

**Issue by andreaskoelsch** [anibali/eval-mpii-pose#18]
Hi,
You are stating that this repo is only for single person evaluation. What confuses me is the fact that the `test.h5` database contains 11,731 persons, while the official `mpii_human_pose_v1_u12_1.mat` file has a total of 11,823 persons annotated as test. Of these, only 7,247 are annotated as single persons. So, I am wondering which format the submission would actually need. I find the documentation quite sparse, but if I understood this (http://human-pose.mpi-inf.mpg.de/#evaluation) correctly, only the 7,247 persons should be predicted in the single-person case.
Could you explain why there are 11,731 persons annotated in `test.h5`?

**Comment by anibali** [comment]
`test.h5` comes from https://github.com/princeton-vl/pose-hg-train/tree/master/data/mpii/annot. As you point out, this file contains 11731 examples. I am not sure exactly how `test.h5` file was generated, but I suppose they must have ignored the `single_person` field. In any case, it doesn't matter too much since when submitting for evaluation if the protocol is to evaluate on the 7247 "single person" cases then the rest will be ignored anyway.

**Comment by andreaskoelsch** [comment]
Thanks, that's what I wanted to get confirmed.

**Comment by andreaskoelsch** [comment]
Sorry to reopen this. So, this means, if I want to use your script for converting my predictions to the acceptable format, my input format has to be a 2 x 16 x 11,731 tensor, right? It just seems wrong, as you explicitly state the scripts are for single-person only.

**Comment by anibali** [comment]
Yes, it has to have 11731 examples. When I created this project, that was the way to go to be compatible with the leading open source 2D pose estimation projects available at the time.

**Comment by andreaskoelsch** [comment]
Okay, sounds reasonable ;-) I guess, I will be able to adjust your code to my needs.
