### ISSUE TITLE
Question in prepareTestResults.m

### ISSUE THREAD

**Issue by 738654805** [anibali/eval-mpii-pose#4]
Thanks for share your code.
Correlation between person centers and thorax predictions in prepareTestResults.m
    0.9893
    0.9083
What's the use of two above?

**Comment by anibali** [comment]
Those values are there as a sanity check. Since the ground truth for the test set is not available, I use correlation between predicted thorax position and annotated person center to roughly indicate whether the annotations seem sensible. High correlation (as you have there) means that everything probably worked correctly.
